#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/tulip

PRODUCT_COPY_FILES += \
    vendor/xiaomi/tulip/proprietary/etc/firmware/goodixfp.b00:$(TARGET_COPY_OUT_ETC)/firmware/goodixfp.b00 \
    vendor/xiaomi/tulip/proprietary/etc/firmware/goodixfp.b01:$(TARGET_COPY_OUT_ETC)/firmware/goodixfp.b01 \
    vendor/xiaomi/tulip/proprietary/etc/firmware/goodixfp.b02:$(TARGET_COPY_OUT_ETC)/firmware/goodixfp.b02 \
    vendor/xiaomi/tulip/proprietary/etc/firmware/goodixfp.b03:$(TARGET_COPY_OUT_ETC)/firmware/goodixfp.b03 \
    vendor/xiaomi/tulip/proprietary/etc/firmware/goodixfp.b04:$(TARGET_COPY_OUT_ETC)/firmware/goodixfp.b04 \
    vendor/xiaomi/tulip/proprietary/etc/firmware/goodixfp.b05:$(TARGET_COPY_OUT_ETC)/firmware/goodixfp.b05 \
    vendor/xiaomi/tulip/proprietary/etc/firmware/goodixfp.b06:$(TARGET_COPY_OUT_ETC)/firmware/goodixfp.b06 \
    vendor/xiaomi/tulip/proprietary/etc/firmware/goodixfp.b07:$(TARGET_COPY_OUT_ETC)/firmware/goodixfp.b07 \
    vendor/xiaomi/tulip/proprietary/etc/firmware/goodixfp.mdt:$(TARGET_COPY_OUT_ETC)/firmware/goodixfp.mdt \
    vendor/xiaomi/tulip/proprietary/vendor/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb \
    vendor/xiaomi/tulip/proprietary/vendor/etc/acdbdata/MTP/MTP_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_General_cal.acdb \
    vendor/xiaomi/tulip/proprietary/vendor/etc/acdbdata/MTP/MTP_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Global_cal.acdb \
    vendor/xiaomi/tulip/proprietary/vendor/etc/acdbdata/MTP/MTP_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Handset_cal.acdb \
    vendor/xiaomi/tulip/proprietary/vendor/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb \
    vendor/xiaomi/tulip/proprietary/vendor/etc/acdbdata/MTP/MTP_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Headset_cal.acdb \
    vendor/xiaomi/tulip/proprietary/vendor/etc/acdbdata/MTP/MTP_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Speaker_cal.acdb \
    vendor/xiaomi/tulip/proprietary/vendor/etc/acdbdata/MTP/MTP_workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_workspaceFile.qwsp \
    vendor/xiaomi/tulip/proprietary/vendor/etc/acdbdata/adsp_avs_config.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/adsp_avs_config.acdb \
    vendor/xiaomi/tulip/proprietary/vendor/etc/camera/GpuKernelRepo.pb:$(TARGET_COPY_OUT_VENDOR)/etc/camera/GpuKernelRepo.pb \
    vendor/xiaomi/tulip/proprietary/vendor/etc/camera/camera_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camera_config.xml \
    vendor/xiaomi/tulip/proprietary/vendor/etc/camera/female_bg.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/female_bg.png \
    vendor/xiaomi/tulip/proprietary/vendor/etc/camera/female_icon.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/female_icon.png \
    vendor/xiaomi/tulip/proprietary/vendor/etc/camera/male_bg.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/male_bg.png \
    vendor/xiaomi/tulip/proprietary/vendor/etc/camera/male_icon.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/male_icon.png \
    vendor/xiaomi/tulip/proprietary/vendor/etc/camera/model_back.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model_back.dlc \
    vendor/xiaomi/tulip/proprietary/vendor/etc/camera/model_front.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model_front.dlc \
    vendor/xiaomi/tulip/proprietary/vendor/etc/camera/score_bg.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/score_bg.png \
    vendor/xiaomi/tulip/proprietary/vendor/etc/camera/score_icon.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/score_icon.png \
    vendor/xiaomi/tulip/proprietary/vendor/etc/camera/tulip_ov02a10_ofilm_global_ii_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/tulip_ov02a10_ofilm_global_ii_chromatix.xml \
    vendor/xiaomi/tulip/proprietary/vendor/etc/camera/tulip_ov02a10_ofilm_india_ii_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/tulip_ov02a10_ofilm_india_ii_chromatix.xml \
    vendor/xiaomi/tulip/proprietary/vendor/etc/camera/tulip_ov02a10_sunny_global_i_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/tulip_ov02a10_sunny_global_i_chromatix.xml \
    vendor/xiaomi/tulip/proprietary/vendor/etc/camera/tulip_ov02a10_sunny_india_i_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/tulip_ov02a10_sunny_india_i_chromatix.xml \
    vendor/xiaomi/tulip/proprietary/vendor/etc/camera/tulip_s5k2l7_ofilm_global_i_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/tulip_s5k2l7_ofilm_global_i_chromatix.xml \
    vendor/xiaomi/tulip/proprietary/vendor/etc/camera/tulip_s5k2l7_ofilm_india_i_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/tulip_s5k2l7_ofilm_india_i_chromatix.xml \
    vendor/xiaomi/tulip/proprietary/vendor/etc/camera/tulip_s5k2l7_qtech_global_ii_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/tulip_s5k2l7_qtech_global_ii_chromatix.xml \
    vendor/xiaomi/tulip/proprietary/vendor/etc/camera/tulip_s5k2l7_qtech_india_ii_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/tulip_s5k2l7_qtech_india_ii_chromatix.xml \
    vendor/xiaomi/tulip/proprietary/vendor/etc/camera/tulip_s5k3T1_ofilm_global_ii_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/tulip_s5k3T1_ofilm_global_ii_chromatix.xml \
    vendor/xiaomi/tulip/proprietary/vendor/etc/camera/tulip_s5k3T1_ofilm_india_ii_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/tulip_s5k3T1_ofilm_india_ii_chromatix.xml \
    vendor/xiaomi/tulip/proprietary/vendor/etc/camera/tulip_s5k3T1_sunny_global_i_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/tulip_s5k3T1_sunny_global_i_chromatix.xml \
    vendor/xiaomi/tulip/proprietary/vendor/etc/camera/tulip_s5k3T1_sunny_india_i_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/tulip_s5k3T1_sunny_india_i_chromatix.xml \
    vendor/xiaomi/tulip/proprietary/vendor/etc/camera/tulip_s5k5e8_ofilm_global_i_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/tulip_s5k5e8_ofilm_global_i_chromatix.xml \
    vendor/xiaomi/tulip/proprietary/vendor/etc/camera/tulip_s5k5e8_ofilm_india_i_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/tulip_s5k5e8_ofilm_india_i_chromatix.xml \
    vendor/xiaomi/tulip/proprietary/vendor/etc/camera/tulip_s5k5e8_qtech_global_ii_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/tulip_s5k5e8_qtech_global_ii_chromatix.xml \
    vendor/xiaomi/tulip/proprietary/vendor/etc/camera/tulip_s5k5e8_qtech_india_ii_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/tulip_s5k5e8_qtech_india_ii_chromatix.xml \
    vendor/xiaomi/tulip/proprietary/vendor/etc/init/android.hardware.keymaster@4.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.keymaster@4.0-service-qti.rc \
    vendor/xiaomi/tulip/proprietary/vendor/etc/permissions/com.fingerprints.extension.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/com.fingerprints.extension.xml \
    vendor/xiaomi/tulip/proprietary/vendor/etc/sensors/hals.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/hals.conf \
    vendor/xiaomi/tulip/proprietary/vendor/etc/sensors/sensor_def_qcomdev.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/sensor_def_qcomdev.conf \
    vendor/xiaomi/tulip/proprietary/vendor/firmware/cpp_firmware_v1_10_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_10_0.fw \
    vendor/xiaomi/tulip/proprietary/vendor/firmware/cpp_firmware_v1_12_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_12_0.fw \
    vendor/xiaomi/tulip/proprietary/vendor/firmware/cpp_firmware_v1_1_1.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_1_1.fw \
    vendor/xiaomi/tulip/proprietary/vendor/firmware/cpp_firmware_v1_1_6.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_1_6.fw \
    vendor/xiaomi/tulip/proprietary/vendor/firmware/cpp_firmware_v1_2_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_2_0.fw \
    vendor/xiaomi/tulip/proprietary/vendor/firmware/cpp_firmware_v1_4_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_4_0.fw \
    vendor/xiaomi/tulip/proprietary/vendor/firmware/cpp_firmware_v1_5_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_0.fw \
    vendor/xiaomi/tulip/proprietary/vendor/firmware/cpp_firmware_v1_5_1.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_1.fw \
    vendor/xiaomi/tulip/proprietary/vendor/firmware/cpp_firmware_v1_5_2.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_2.fw \
    vendor/xiaomi/tulip/proprietary/vendor/firmware/cpp_firmware_v1_6_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_6_0.fw \
    vendor/xiaomi/tulip/proprietary/vendor/firmware/cpp_firmware_v1_8_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_8_0.fw \
    vendor/xiaomi/tulip/proprietary/vendor/firmware/fpctzappfingerprint.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzappfingerprint.b00 \
    vendor/xiaomi/tulip/proprietary/vendor/firmware/fpctzappfingerprint.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzappfingerprint.b01 \
    vendor/xiaomi/tulip/proprietary/vendor/firmware/fpctzappfingerprint.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzappfingerprint.b02 \
    vendor/xiaomi/tulip/proprietary/vendor/firmware/fpctzappfingerprint.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzappfingerprint.b03 \
    vendor/xiaomi/tulip/proprietary/vendor/firmware/fpctzappfingerprint.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzappfingerprint.b04 \
    vendor/xiaomi/tulip/proprietary/vendor/firmware/fpctzappfingerprint.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzappfingerprint.b05 \
    vendor/xiaomi/tulip/proprietary/vendor/firmware/fpctzappfingerprint.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzappfingerprint.b06 \
    vendor/xiaomi/tulip/proprietary/vendor/firmware/fpctzappfingerprint.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzappfingerprint.b07 \
    vendor/xiaomi/tulip/proprietary/vendor/firmware/fpctzappfingerprint.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzappfingerprint.mdt \
    vendor/xiaomi/tulip/proprietary/vendor/firmware/tas2557_uCDSP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/tas2557_uCDSP.bin

PRODUCT_PACKAGES += \
    keystore.sdm660 \
    vendor.qti.hardware.fingerprint@1.0 \
    camera.sdm660 \
    libMiWatermark \
    libSNPE \
    libSonyIMX376C3RmscLibrary \
    libSonyIMX376KRmscLibrary \
    libVDClearShot \
    libVDSuperPhotoAPI \
    libXMFD_AgeGender \
    lib_lowlight \
    libactuator_tulip_s5k2l7_ofilm_i_ak7374 \
    libactuator_tulip_s5k2l7_qtech_ii_ak7374 \
    libarcsoft_beautyshot \
    libarcsoft_dualcam_refocus \
    libarcsoft_dualcam_refocus_front \
    libarcsoft_dualcam_refocus_rear_t \
    libarcsoft_high_dynamic_range \
    libc++_shared \
    libcamera_scene \
    libchromatix_tulip_ov02a10_ofilm_global_ii_common \
    libchromatix_tulip_ov02a10_ofilm_global_ii_cpp_liveshot \
    libchromatix_tulip_ov02a10_ofilm_global_ii_cpp_preview \
    libchromatix_tulip_ov02a10_ofilm_global_ii_cpp_snapshot \
    libchromatix_tulip_ov02a10_ofilm_global_ii_cpp_video \
    libchromatix_tulip_ov02a10_ofilm_global_ii_postproc \
    libchromatix_tulip_ov02a10_ofilm_global_ii_preview \
    libchromatix_tulip_ov02a10_ofilm_global_ii_snapshot \
    libchromatix_tulip_ov02a10_ofilm_global_ii_video \
    libchromatix_tulip_ov02a10_ofilm_global_ii_zsl_preview_3a \
    libchromatix_tulip_ov02a10_ofilm_global_ii_zsl_video_3a \
    libchromatix_tulip_ov02a10_ofilm_india_ii_common \
    libchromatix_tulip_ov02a10_ofilm_india_ii_cpp_liveshot \
    libchromatix_tulip_ov02a10_ofilm_india_ii_cpp_preview \
    libchromatix_tulip_ov02a10_ofilm_india_ii_cpp_snapshot \
    libchromatix_tulip_ov02a10_ofilm_india_ii_cpp_video \
    libchromatix_tulip_ov02a10_ofilm_india_ii_postproc \
    libchromatix_tulip_ov02a10_ofilm_india_ii_preview \
    libchromatix_tulip_ov02a10_ofilm_india_ii_snapshot \
    libchromatix_tulip_ov02a10_ofilm_india_ii_video \
    libchromatix_tulip_ov02a10_ofilm_india_ii_zsl_preview_3a \
    libchromatix_tulip_ov02a10_ofilm_india_ii_zsl_video_3a \
    libchromatix_tulip_ov02a10_sunny_global_i_common \
    libchromatix_tulip_ov02a10_sunny_global_i_cpp_liveshot \
    libchromatix_tulip_ov02a10_sunny_global_i_cpp_preview \
    libchromatix_tulip_ov02a10_sunny_global_i_cpp_snapshot \
    libchromatix_tulip_ov02a10_sunny_global_i_cpp_video \
    libchromatix_tulip_ov02a10_sunny_global_i_postproc \
    libchromatix_tulip_ov02a10_sunny_global_i_preview \
    libchromatix_tulip_ov02a10_sunny_global_i_snapshot \
    libchromatix_tulip_ov02a10_sunny_global_i_video \
    libchromatix_tulip_ov02a10_sunny_global_i_zsl_preview_3a \
    libchromatix_tulip_ov02a10_sunny_global_i_zsl_video_3a \
    libchromatix_tulip_ov02a10_sunny_india_i_common \
    libchromatix_tulip_ov02a10_sunny_india_i_cpp_liveshot \
    libchromatix_tulip_ov02a10_sunny_india_i_cpp_preview \
    libchromatix_tulip_ov02a10_sunny_india_i_cpp_snapshot \
    libchromatix_tulip_ov02a10_sunny_india_i_cpp_video \
    libchromatix_tulip_ov02a10_sunny_india_i_postproc \
    libchromatix_tulip_ov02a10_sunny_india_i_preview \
    libchromatix_tulip_ov02a10_sunny_india_i_snapshot \
    libchromatix_tulip_ov02a10_sunny_india_i_video \
    libchromatix_tulip_ov02a10_sunny_india_i_zsl_preview_3a \
    libchromatix_tulip_ov02a10_sunny_india_i_zsl_video_3a \
    libchromatix_tulip_s5k2l7_ofilm_global_i_4k_preview_3a \
    libchromatix_tulip_s5k2l7_ofilm_global_i_4k_video_3a \
    libchromatix_tulip_s5k2l7_ofilm_global_i_bokeh_preview \
    libchromatix_tulip_s5k2l7_ofilm_global_i_bokeh_preview_3a \
    libchromatix_tulip_s5k2l7_ofilm_global_i_bokeh_snapshot \
    libchromatix_tulip_s5k2l7_ofilm_global_i_common \
    libchromatix_tulip_s5k2l7_ofilm_global_i_cpp_hfr_120 \
    libchromatix_tulip_s5k2l7_ofilm_global_i_cpp_hfr_240 \
    libchromatix_tulip_s5k2l7_ofilm_global_i_cpp_hfr_60 \
    libchromatix_tulip_s5k2l7_ofilm_global_i_cpp_hfr_90 \
    libchromatix_tulip_s5k2l7_ofilm_global_i_cpp_liveshot \
    libchromatix_tulip_s5k2l7_ofilm_global_i_cpp_preview \
    libchromatix_tulip_s5k2l7_ofilm_global_i_cpp_snapshot \
    libchromatix_tulip_s5k2l7_ofilm_global_i_cpp_snapshot_bokeh \
    libchromatix_tulip_s5k2l7_ofilm_global_i_cpp_snapshot_hdr \
    libchromatix_tulip_s5k2l7_ofilm_global_i_cpp_snapshot_hht \
    libchromatix_tulip_s5k2l7_ofilm_global_i_cpp_video \
    libchromatix_tulip_s5k2l7_ofilm_global_i_cpp_video_4k \
    libchromatix_tulip_s5k2l7_ofilm_global_i_cpp_video_weixin \
    libchromatix_tulip_s5k2l7_ofilm_global_i_default_preview_3a \
    libchromatix_tulip_s5k2l7_ofilm_global_i_default_video_3a \
    libchromatix_tulip_s5k2l7_ofilm_global_i_hfr_120 \
    libchromatix_tulip_s5k2l7_ofilm_global_i_hfr_120_3a \
    libchromatix_tulip_s5k2l7_ofilm_global_i_hfr_240 \
    libchromatix_tulip_s5k2l7_ofilm_global_i_hfr_240_3a \
    libchromatix_tulip_s5k2l7_ofilm_global_i_hfr_60 \
    libchromatix_tulip_s5k2l7_ofilm_global_i_hfr_60_3a \
    libchromatix_tulip_s5k2l7_ofilm_global_i_hfr_90 \
    libchromatix_tulip_s5k2l7_ofilm_global_i_hfr_90_3a \
    libchromatix_tulip_s5k2l7_ofilm_global_i_pano_preview_3a \
    libchromatix_tulip_s5k2l7_ofilm_global_i_postproc \
    libchromatix_tulip_s5k2l7_ofilm_global_i_preview \
    libchromatix_tulip_s5k2l7_ofilm_global_i_snapshot \
    libchromatix_tulip_s5k2l7_ofilm_global_i_snapshot_hdr \
    libchromatix_tulip_s5k2l7_ofilm_global_i_video \
    libchromatix_tulip_s5k2l7_ofilm_global_i_video_4k \
    libchromatix_tulip_s5k2l7_ofilm_global_i_video_weixin \
    libchromatix_tulip_s5k2l7_ofilm_global_i_weixin_video_3a \
    libchromatix_tulip_s5k2l7_ofilm_global_i_zsl_preview_3a \
    libchromatix_tulip_s5k2l7_ofilm_global_i_zsl_video_3a \
    libchromatix_tulip_s5k2l7_ofilm_india_i_4k_preview_3a \
    libchromatix_tulip_s5k2l7_ofilm_india_i_4k_video_3a \
    libchromatix_tulip_s5k2l7_ofilm_india_i_bokeh_preview \
    libchromatix_tulip_s5k2l7_ofilm_india_i_bokeh_preview_3a \
    libchromatix_tulip_s5k2l7_ofilm_india_i_bokeh_snapshot \
    libchromatix_tulip_s5k2l7_ofilm_india_i_common \
    libchromatix_tulip_s5k2l7_ofilm_india_i_cpp_hfr_120 \
    libchromatix_tulip_s5k2l7_ofilm_india_i_cpp_hfr_240 \
    libchromatix_tulip_s5k2l7_ofilm_india_i_cpp_hfr_60 \
    libchromatix_tulip_s5k2l7_ofilm_india_i_cpp_hfr_90 \
    libchromatix_tulip_s5k2l7_ofilm_india_i_cpp_liveshot \
    libchromatix_tulip_s5k2l7_ofilm_india_i_cpp_preview \
    libchromatix_tulip_s5k2l7_ofilm_india_i_cpp_snapshot \
    libchromatix_tulip_s5k2l7_ofilm_india_i_cpp_snapshot_bokeh \
    libchromatix_tulip_s5k2l7_ofilm_india_i_cpp_snapshot_hdr \
    libchromatix_tulip_s5k2l7_ofilm_india_i_cpp_snapshot_hht \
    libchromatix_tulip_s5k2l7_ofilm_india_i_cpp_video \
    libchromatix_tulip_s5k2l7_ofilm_india_i_cpp_video_4k \
    libchromatix_tulip_s5k2l7_ofilm_india_i_cpp_video_weixin \
    libchromatix_tulip_s5k2l7_ofilm_india_i_default_preview_3a \
    libchromatix_tulip_s5k2l7_ofilm_india_i_default_video_3a \
    libchromatix_tulip_s5k2l7_ofilm_india_i_hfr_120 \
    libchromatix_tulip_s5k2l7_ofilm_india_i_hfr_120_3a \
    libchromatix_tulip_s5k2l7_ofilm_india_i_hfr_240 \
    libchromatix_tulip_s5k2l7_ofilm_india_i_hfr_240_3a \
    libchromatix_tulip_s5k2l7_ofilm_india_i_hfr_60 \
    libchromatix_tulip_s5k2l7_ofilm_india_i_hfr_60_3a \
    libchromatix_tulip_s5k2l7_ofilm_india_i_hfr_90 \
    libchromatix_tulip_s5k2l7_ofilm_india_i_hfr_90_3a \
    libchromatix_tulip_s5k2l7_ofilm_india_i_pano_preview_3a \
    libchromatix_tulip_s5k2l7_ofilm_india_i_postproc \
    libchromatix_tulip_s5k2l7_ofilm_india_i_preview \
    libchromatix_tulip_s5k2l7_ofilm_india_i_snapshot \
    libchromatix_tulip_s5k2l7_ofilm_india_i_snapshot_hdr \
    libchromatix_tulip_s5k2l7_ofilm_india_i_video \
    libchromatix_tulip_s5k2l7_ofilm_india_i_video_4k \
    libchromatix_tulip_s5k2l7_ofilm_india_i_video_weixin \
    libchromatix_tulip_s5k2l7_ofilm_india_i_weixin_video_3a \
    libchromatix_tulip_s5k2l7_ofilm_india_i_zsl_preview_3a \
    libchromatix_tulip_s5k2l7_ofilm_india_i_zsl_video_3a \
    libchromatix_tulip_s5k2l7_qtech_global_ii_4k_preview_3a \
    libchromatix_tulip_s5k2l7_qtech_global_ii_4k_video_3a \
    libchromatix_tulip_s5k2l7_qtech_global_ii_bokeh_preview \
    libchromatix_tulip_s5k2l7_qtech_global_ii_bokeh_preview_3a \
    libchromatix_tulip_s5k2l7_qtech_global_ii_bokeh_snapshot \
    libchromatix_tulip_s5k2l7_qtech_global_ii_common \
    libchromatix_tulip_s5k2l7_qtech_global_ii_cpp_hfr_120 \
    libchromatix_tulip_s5k2l7_qtech_global_ii_cpp_hfr_240 \
    libchromatix_tulip_s5k2l7_qtech_global_ii_cpp_hfr_60 \
    libchromatix_tulip_s5k2l7_qtech_global_ii_cpp_hfr_90 \
    libchromatix_tulip_s5k2l7_qtech_global_ii_cpp_liveshot \
    libchromatix_tulip_s5k2l7_qtech_global_ii_cpp_preview \
    libchromatix_tulip_s5k2l7_qtech_global_ii_cpp_snapshot \
    libchromatix_tulip_s5k2l7_qtech_global_ii_cpp_snapshot_bokeh \
    libchromatix_tulip_s5k2l7_qtech_global_ii_cpp_snapshot_hdr \
    libchromatix_tulip_s5k2l7_qtech_global_ii_cpp_snapshot_hht \
    libchromatix_tulip_s5k2l7_qtech_global_ii_cpp_video \
    libchromatix_tulip_s5k2l7_qtech_global_ii_cpp_video_4k \
    libchromatix_tulip_s5k2l7_qtech_global_ii_cpp_video_weixin \
    libchromatix_tulip_s5k2l7_qtech_global_ii_default_preview_3a \
    libchromatix_tulip_s5k2l7_qtech_global_ii_default_video_3a \
    libchromatix_tulip_s5k2l7_qtech_global_ii_hfr_120 \
    libchromatix_tulip_s5k2l7_qtech_global_ii_hfr_120_3a \
    libchromatix_tulip_s5k2l7_qtech_global_ii_hfr_240 \
    libchromatix_tulip_s5k2l7_qtech_global_ii_hfr_240_3a \
    libchromatix_tulip_s5k2l7_qtech_global_ii_hfr_60 \
    libchromatix_tulip_s5k2l7_qtech_global_ii_hfr_60_3a \
    libchromatix_tulip_s5k2l7_qtech_global_ii_hfr_90 \
    libchromatix_tulip_s5k2l7_qtech_global_ii_hfr_90_3a \
    libchromatix_tulip_s5k2l7_qtech_global_ii_pano_preview_3a \
    libchromatix_tulip_s5k2l7_qtech_global_ii_postproc \
    libchromatix_tulip_s5k2l7_qtech_global_ii_preview \
    libchromatix_tulip_s5k2l7_qtech_global_ii_snapshot \
    libchromatix_tulip_s5k2l7_qtech_global_ii_snapshot_hdr \
    libchromatix_tulip_s5k2l7_qtech_global_ii_video \
    libchromatix_tulip_s5k2l7_qtech_global_ii_video_4k \
    libchromatix_tulip_s5k2l7_qtech_global_ii_video_weixin \
    libchromatix_tulip_s5k2l7_qtech_global_ii_weixin_video_3a \
    libchromatix_tulip_s5k2l7_qtech_global_ii_zsl_preview_3a \
    libchromatix_tulip_s5k2l7_qtech_global_ii_zsl_video_3a \
    libchromatix_tulip_s5k2l7_qtech_india_ii_4k_preview_3a \
    libchromatix_tulip_s5k2l7_qtech_india_ii_4k_video_3a \
    libchromatix_tulip_s5k2l7_qtech_india_ii_bokeh_preview \
    libchromatix_tulip_s5k2l7_qtech_india_ii_bokeh_preview_3a \
    libchromatix_tulip_s5k2l7_qtech_india_ii_bokeh_snapshot \
    libchromatix_tulip_s5k2l7_qtech_india_ii_common \
    libchromatix_tulip_s5k2l7_qtech_india_ii_cpp_hfr_120 \
    libchromatix_tulip_s5k2l7_qtech_india_ii_cpp_hfr_240 \
    libchromatix_tulip_s5k2l7_qtech_india_ii_cpp_hfr_60 \
    libchromatix_tulip_s5k2l7_qtech_india_ii_cpp_hfr_90 \
    libchromatix_tulip_s5k2l7_qtech_india_ii_cpp_liveshot \
    libchromatix_tulip_s5k2l7_qtech_india_ii_cpp_preview \
    libchromatix_tulip_s5k2l7_qtech_india_ii_cpp_snapshot \
    libchromatix_tulip_s5k2l7_qtech_india_ii_cpp_snapshot_bokeh \
    libchromatix_tulip_s5k2l7_qtech_india_ii_cpp_snapshot_hdr \
    libchromatix_tulip_s5k2l7_qtech_india_ii_cpp_snapshot_hht \
    libchromatix_tulip_s5k2l7_qtech_india_ii_cpp_video \
    libchromatix_tulip_s5k2l7_qtech_india_ii_cpp_video_4k \
    libchromatix_tulip_s5k2l7_qtech_india_ii_cpp_video_weixin \
    libchromatix_tulip_s5k2l7_qtech_india_ii_default_preview_3a \
    libchromatix_tulip_s5k2l7_qtech_india_ii_default_video_3a \
    libchromatix_tulip_s5k2l7_qtech_india_ii_hfr_120 \
    libchromatix_tulip_s5k2l7_qtech_india_ii_hfr_120_3a \
    libchromatix_tulip_s5k2l7_qtech_india_ii_hfr_240 \
    libchromatix_tulip_s5k2l7_qtech_india_ii_hfr_240_3a \
    libchromatix_tulip_s5k2l7_qtech_india_ii_hfr_60 \
    libchromatix_tulip_s5k2l7_qtech_india_ii_hfr_60_3a \
    libchromatix_tulip_s5k2l7_qtech_india_ii_hfr_90 \
    libchromatix_tulip_s5k2l7_qtech_india_ii_hfr_90_3a \
    libchromatix_tulip_s5k2l7_qtech_india_ii_pano_preview_3a \
    libchromatix_tulip_s5k2l7_qtech_india_ii_postproc \
    libchromatix_tulip_s5k2l7_qtech_india_ii_preview \
    libchromatix_tulip_s5k2l7_qtech_india_ii_snapshot \
    libchromatix_tulip_s5k2l7_qtech_india_ii_snapshot_hdr \
    libchromatix_tulip_s5k2l7_qtech_india_ii_video \
    libchromatix_tulip_s5k2l7_qtech_india_ii_video_4k \
    libchromatix_tulip_s5k2l7_qtech_india_ii_video_weixin \
    libchromatix_tulip_s5k2l7_qtech_india_ii_weixin_video_3a \
    libchromatix_tulip_s5k2l7_qtech_india_ii_zsl_preview_3a \
    libchromatix_tulip_s5k2l7_qtech_india_ii_zsl_video_3a \
    libchromatix_tulip_s5k3T1_ofilm_global_ii_bokeh_preview \
    libchromatix_tulip_s5k3T1_ofilm_global_ii_bokeh_snapshot \
    libchromatix_tulip_s5k3T1_ofilm_global_ii_common \
    libchromatix_tulip_s5k3T1_ofilm_global_ii_cpp_liveshot \
    libchromatix_tulip_s5k3T1_ofilm_global_ii_cpp_preview \
    libchromatix_tulip_s5k3T1_ofilm_global_ii_cpp_snapshot \
    libchromatix_tulip_s5k3T1_ofilm_global_ii_cpp_snapshot_5M \
    libchromatix_tulip_s5k3T1_ofilm_global_ii_cpp_snapshot_5M_hht \
    libchromatix_tulip_s5k3T1_ofilm_global_ii_cpp_snapshot_bokeh \
    libchromatix_tulip_s5k3T1_ofilm_global_ii_cpp_snapshot_downscale \
    libchromatix_tulip_s5k3T1_ofilm_global_ii_cpp_snapshot_hdr \
    libchromatix_tulip_s5k3T1_ofilm_global_ii_cpp_snapshot_upscale \
    libchromatix_tulip_s5k3T1_ofilm_global_ii_cpp_video \
    libchromatix_tulip_s5k3T1_ofilm_global_ii_cpp_video_default \
    libchromatix_tulip_s5k3T1_ofilm_global_ii_cpp_video_face \
    libchromatix_tulip_s5k3T1_ofilm_global_ii_cpp_video_weixin \
    libchromatix_tulip_s5k3T1_ofilm_global_ii_default_bokeh_preview_3a \
    libchromatix_tulip_s5k3T1_ofilm_global_ii_default_preview_3a \
    libchromatix_tulip_s5k3T1_ofilm_global_ii_default_video_3a \
    libchromatix_tulip_s5k3T1_ofilm_global_ii_face_video_3a \
    libchromatix_tulip_s5k3T1_ofilm_global_ii_fullsize_preview_3a \
    libchromatix_tulip_s5k3T1_ofilm_global_ii_fullsize_video_3a \
    libchromatix_tulip_s5k3T1_ofilm_global_ii_hdr_preview_3a \
    libchromatix_tulip_s5k3T1_ofilm_global_ii_hdr_video_3a \
    libchromatix_tulip_s5k3T1_ofilm_global_ii_postproc \
    libchromatix_tulip_s5k3T1_ofilm_global_ii_preview \
    libchromatix_tulip_s5k3T1_ofilm_global_ii_snapshot \
    libchromatix_tulip_s5k3T1_ofilm_global_ii_snapshot_hdr \
    libchromatix_tulip_s5k3T1_ofilm_global_ii_video_default \
    libchromatix_tulip_s5k3T1_ofilm_global_ii_video_face \
    libchromatix_tulip_s5k3T1_ofilm_global_ii_video_weixin \
    libchromatix_tulip_s5k3T1_ofilm_global_ii_weixin_video_3a \
    libchromatix_tulip_s5k3T1_ofilm_india_ii_bokeh_preview \
    libchromatix_tulip_s5k3T1_ofilm_india_ii_bokeh_snapshot \
    libchromatix_tulip_s5k3T1_ofilm_india_ii_common \
    libchromatix_tulip_s5k3T1_ofilm_india_ii_cpp_liveshot \
    libchromatix_tulip_s5k3T1_ofilm_india_ii_cpp_preview \
    libchromatix_tulip_s5k3T1_ofilm_india_ii_cpp_snapshot \
    libchromatix_tulip_s5k3T1_ofilm_india_ii_cpp_snapshot_5M \
    libchromatix_tulip_s5k3T1_ofilm_india_ii_cpp_snapshot_5M_hht \
    libchromatix_tulip_s5k3T1_ofilm_india_ii_cpp_snapshot_bokeh \
    libchromatix_tulip_s5k3T1_ofilm_india_ii_cpp_snapshot_downscale \
    libchromatix_tulip_s5k3T1_ofilm_india_ii_cpp_snapshot_hdr \
    libchromatix_tulip_s5k3T1_ofilm_india_ii_cpp_snapshot_upscale \
    libchromatix_tulip_s5k3T1_ofilm_india_ii_cpp_video \
    libchromatix_tulip_s5k3T1_ofilm_india_ii_cpp_video_default \
    libchromatix_tulip_s5k3T1_ofilm_india_ii_cpp_video_face \
    libchromatix_tulip_s5k3T1_ofilm_india_ii_cpp_video_weixin \
    libchromatix_tulip_s5k3T1_ofilm_india_ii_default_bokeh_preview_3a \
    libchromatix_tulip_s5k3T1_ofilm_india_ii_default_preview_3a \
    libchromatix_tulip_s5k3T1_ofilm_india_ii_default_video_3a \
    libchromatix_tulip_s5k3T1_ofilm_india_ii_face_video_3a \
    libchromatix_tulip_s5k3T1_ofilm_india_ii_fullsize_preview_3a \
    libchromatix_tulip_s5k3T1_ofilm_india_ii_fullsize_video_3a \
    libchromatix_tulip_s5k3T1_ofilm_india_ii_hdr_preview_3a \
    libchromatix_tulip_s5k3T1_ofilm_india_ii_hdr_video_3a \
    libchromatix_tulip_s5k3T1_ofilm_india_ii_postproc \
    libchromatix_tulip_s5k3T1_ofilm_india_ii_preview \
    libchromatix_tulip_s5k3T1_ofilm_india_ii_snapshot \
    libchromatix_tulip_s5k3T1_ofilm_india_ii_snapshot_hdr \
    libchromatix_tulip_s5k3T1_ofilm_india_ii_video_default \
    libchromatix_tulip_s5k3T1_ofilm_india_ii_video_face \
    libchromatix_tulip_s5k3T1_ofilm_india_ii_video_weixin \
    libchromatix_tulip_s5k3T1_ofilm_india_ii_weixin_video_3a \
    libchromatix_tulip_s5k3T1_sunny_global_i_bokeh_preview \
    libchromatix_tulip_s5k3T1_sunny_global_i_bokeh_snapshot \
    libchromatix_tulip_s5k3T1_sunny_global_i_common \
    libchromatix_tulip_s5k3T1_sunny_global_i_cpp_liveshot \
    libchromatix_tulip_s5k3T1_sunny_global_i_cpp_preview \
    libchromatix_tulip_s5k3T1_sunny_global_i_cpp_snapshot \
    libchromatix_tulip_s5k3T1_sunny_global_i_cpp_snapshot_5M \
    libchromatix_tulip_s5k3T1_sunny_global_i_cpp_snapshot_5M_hht \
    libchromatix_tulip_s5k3T1_sunny_global_i_cpp_snapshot_bokeh \
    libchromatix_tulip_s5k3T1_sunny_global_i_cpp_snapshot_downscale \
    libchromatix_tulip_s5k3T1_sunny_global_i_cpp_snapshot_hdr \
    libchromatix_tulip_s5k3T1_sunny_global_i_cpp_snapshot_upscale \
    libchromatix_tulip_s5k3T1_sunny_global_i_cpp_video \
    libchromatix_tulip_s5k3T1_sunny_global_i_cpp_video_default \
    libchromatix_tulip_s5k3T1_sunny_global_i_cpp_video_face \
    libchromatix_tulip_s5k3T1_sunny_global_i_cpp_video_weixin \
    libchromatix_tulip_s5k3T1_sunny_global_i_default_bokeh_preview_3a \
    libchromatix_tulip_s5k3T1_sunny_global_i_default_preview_3a \
    libchromatix_tulip_s5k3T1_sunny_global_i_default_video_3a \
    libchromatix_tulip_s5k3T1_sunny_global_i_face_video_3a \
    libchromatix_tulip_s5k3T1_sunny_global_i_fullsize_preview_3a \
    libchromatix_tulip_s5k3T1_sunny_global_i_fullsize_video_3a \
    libchromatix_tulip_s5k3T1_sunny_global_i_hdr_preview_3a \
    libchromatix_tulip_s5k3T1_sunny_global_i_hdr_video_3a \
    libchromatix_tulip_s5k3T1_sunny_global_i_postproc \
    libchromatix_tulip_s5k3T1_sunny_global_i_preview \
    libchromatix_tulip_s5k3T1_sunny_global_i_snapshot \
    libchromatix_tulip_s5k3T1_sunny_global_i_snapshot_hdr \
    libchromatix_tulip_s5k3T1_sunny_global_i_video_default \
    libchromatix_tulip_s5k3T1_sunny_global_i_video_face \
    libchromatix_tulip_s5k3T1_sunny_global_i_video_weixin \
    libchromatix_tulip_s5k3T1_sunny_global_i_weixin_video_3a \
    libchromatix_tulip_s5k3T1_sunny_india_i_bokeh_preview \
    libchromatix_tulip_s5k3T1_sunny_india_i_bokeh_snapshot \
    libchromatix_tulip_s5k3T1_sunny_india_i_common \
    libchromatix_tulip_s5k3T1_sunny_india_i_cpp_liveshot \
    libchromatix_tulip_s5k3T1_sunny_india_i_cpp_preview \
    libchromatix_tulip_s5k3T1_sunny_india_i_cpp_snapshot \
    libchromatix_tulip_s5k3T1_sunny_india_i_cpp_snapshot_5M \
    libchromatix_tulip_s5k3T1_sunny_india_i_cpp_snapshot_5M_hht \
    libchromatix_tulip_s5k3T1_sunny_india_i_cpp_snapshot_bokeh \
    libchromatix_tulip_s5k3T1_sunny_india_i_cpp_snapshot_downscale \
    libchromatix_tulip_s5k3T1_sunny_india_i_cpp_snapshot_hdr \
    libchromatix_tulip_s5k3T1_sunny_india_i_cpp_snapshot_upscale \
    libchromatix_tulip_s5k3T1_sunny_india_i_cpp_video \
    libchromatix_tulip_s5k3T1_sunny_india_i_cpp_video_default \
    libchromatix_tulip_s5k3T1_sunny_india_i_cpp_video_face \
    libchromatix_tulip_s5k3T1_sunny_india_i_cpp_video_weixin \
    libchromatix_tulip_s5k3T1_sunny_india_i_default_bokeh_preview_3a \
    libchromatix_tulip_s5k3T1_sunny_india_i_default_preview_3a \
    libchromatix_tulip_s5k3T1_sunny_india_i_default_video_3a \
    libchromatix_tulip_s5k3T1_sunny_india_i_face_video_3a \
    libchromatix_tulip_s5k3T1_sunny_india_i_fullsize_preview_3a \
    libchromatix_tulip_s5k3T1_sunny_india_i_fullsize_video_3a \
    libchromatix_tulip_s5k3T1_sunny_india_i_hdr_preview_3a \
    libchromatix_tulip_s5k3T1_sunny_india_i_hdr_video_3a \
    libchromatix_tulip_s5k3T1_sunny_india_i_postproc \
    libchromatix_tulip_s5k3T1_sunny_india_i_preview \
    libchromatix_tulip_s5k3T1_sunny_india_i_snapshot \
    libchromatix_tulip_s5k3T1_sunny_india_i_snapshot_hdr \
    libchromatix_tulip_s5k3T1_sunny_india_i_video_default \
    libchromatix_tulip_s5k3T1_sunny_india_i_video_face \
    libchromatix_tulip_s5k3T1_sunny_india_i_video_weixin \
    libchromatix_tulip_s5k3T1_sunny_india_i_weixin_video_3a \
    libchromatix_tulip_s5k5e8_ofilm_global_i_common \
    libchromatix_tulip_s5k5e8_ofilm_global_i_cpp_liveshot \
    libchromatix_tulip_s5k5e8_ofilm_global_i_cpp_preview \
    libchromatix_tulip_s5k5e8_ofilm_global_i_cpp_snapshot \
    libchromatix_tulip_s5k5e8_ofilm_global_i_cpp_video_full \
    libchromatix_tulip_s5k5e8_ofilm_global_i_postproc \
    libchromatix_tulip_s5k5e8_ofilm_global_i_preview \
    libchromatix_tulip_s5k5e8_ofilm_global_i_snapshot \
    libchromatix_tulip_s5k5e8_ofilm_global_i_video_full \
    libchromatix_tulip_s5k5e8_ofilm_global_i_zsl_preview \
    libchromatix_tulip_s5k5e8_ofilm_global_i_zsl_video \
    libchromatix_tulip_s5k5e8_ofilm_india_i_common \
    libchromatix_tulip_s5k5e8_ofilm_india_i_cpp_liveshot \
    libchromatix_tulip_s5k5e8_ofilm_india_i_cpp_preview \
    libchromatix_tulip_s5k5e8_ofilm_india_i_cpp_snapshot \
    libchromatix_tulip_s5k5e8_ofilm_india_i_cpp_video_full \
    libchromatix_tulip_s5k5e8_ofilm_india_i_postproc \
    libchromatix_tulip_s5k5e8_ofilm_india_i_preview \
    libchromatix_tulip_s5k5e8_ofilm_india_i_snapshot \
    libchromatix_tulip_s5k5e8_ofilm_india_i_video_full \
    libchromatix_tulip_s5k5e8_ofilm_india_i_zsl_preview \
    libchromatix_tulip_s5k5e8_ofilm_india_i_zsl_video \
    libchromatix_tulip_s5k5e8_qtech_global_ii_common \
    libchromatix_tulip_s5k5e8_qtech_global_ii_cpp_liveshot \
    libchromatix_tulip_s5k5e8_qtech_global_ii_cpp_preview \
    libchromatix_tulip_s5k5e8_qtech_global_ii_cpp_snapshot \
    libchromatix_tulip_s5k5e8_qtech_global_ii_cpp_video_full \
    libchromatix_tulip_s5k5e8_qtech_global_ii_postproc \
    libchromatix_tulip_s5k5e8_qtech_global_ii_preview \
    libchromatix_tulip_s5k5e8_qtech_global_ii_snapshot \
    libchromatix_tulip_s5k5e8_qtech_global_ii_video_full \
    libchromatix_tulip_s5k5e8_qtech_global_ii_zsl_preview \
    libchromatix_tulip_s5k5e8_qtech_global_ii_zsl_video \
    libchromatix_tulip_s5k5e8_qtech_india_ii_common \
    libchromatix_tulip_s5k5e8_qtech_india_ii_cpp_liveshot \
    libchromatix_tulip_s5k5e8_qtech_india_ii_cpp_preview \
    libchromatix_tulip_s5k5e8_qtech_india_ii_cpp_snapshot \
    libchromatix_tulip_s5k5e8_qtech_india_ii_cpp_video_full \
    libchromatix_tulip_s5k5e8_qtech_india_ii_postproc \
    libchromatix_tulip_s5k5e8_qtech_india_ii_preview \
    libchromatix_tulip_s5k5e8_qtech_india_ii_snapshot \
    libchromatix_tulip_s5k5e8_qtech_india_ii_video_full \
    libchromatix_tulip_s5k5e8_qtech_india_ii_zsl_preview \
    libchromatix_tulip_s5k5e8_qtech_india_ii_zsl_video \
    libdepthmapwrapper \
    libflash_pmic \
    libft2vendor \
    libhal_dbg \
    libjpegdhw \
    libjpegdmahw \
    libjpegehw \
    libmibokeh_660 \
    libmm-qcamera \
    libmmcamera2_c2d_module \
    libmmcamera2_cpp_module \
    libmmcamera2_frame_algorithm \
    libmmcamera2_iface_modules \
    libmmcamera2_imglib_modules \
    libmmcamera2_is \
    libmmcamera2_isp_modules \
    libmmcamera2_mct \
    libmmcamera2_mct_shimlayer \
    libmmcamera2_pp_buf_mgr \
    libmmcamera2_pproc_modules \
    libmmcamera2_q3a_core \
    libmmcamera2_sensor_modules \
    libmmcamera2_stats_algorithm \
    libmmcamera2_stats_lib \
    libmmcamera2_stats_modules \
    libmmcamera_arcsoftbokeh_lib \
    libmmcamera_atmel_at24c32e_eeprom \
    libmmcamera_bokeh \
    libmmcamera_depth_map \
    libmmcamera_dummyalgo \
    libmmcamera_eebinparse \
    libmmcamera_eeprom_util \
    libmmcamera_eztune_module \
    libmmcamera_facedetection_lib \
    libmmcamera_faceproc \
    libmmcamera_faceproc2 \
    libmmcamera_hdr_gb_lib \
    libmmcamera_hvx_add_constant \
    libmmcamera_hvx_grid_sum \
    libmmcamera_imglib \
    libmmcamera_imglib_faceproc_adspstub \
    libmmcamera_interface \
    libmmcamera_isp_abf48 \
    libmmcamera_isp_aec_bg_stats47 \
    libmmcamera_isp_bf_stats47 \
    libmmcamera_isp_bg_stats46 \
    libmmcamera_isp_bhist_stats44 \
    libmmcamera_isp_black_level48 \
    libmmcamera_isp_bpc48 \
    libmmcamera_isp_cac47 \
    libmmcamera_isp_chroma_enhan40 \
    libmmcamera_isp_chroma_suppress40 \
    libmmcamera_isp_clamp_encoder40 \
    libmmcamera_isp_clamp_video40 \
    libmmcamera_isp_clamp_viewfinder40 \
    libmmcamera_isp_color_correct46 \
    libmmcamera_isp_color_xform_encoder46 \
    libmmcamera_isp_color_xform_video46 \
    libmmcamera_isp_color_xform_viewfinder46 \
    libmmcamera_isp_cs_stats46 \
    libmmcamera_isp_demosaic48 \
    libmmcamera_isp_demux48 \
    libmmcamera_isp_fovcrop_encoder46 \
    libmmcamera_isp_fovcrop_video46 \
    libmmcamera_isp_fovcrop_viewfinder46 \
    libmmcamera_isp_gamma44 \
    libmmcamera_isp_gic48 \
    libmmcamera_isp_gtm46 \
    libmmcamera_isp_hdr48 \
    libmmcamera_isp_hdr_be_stats46 \
    libmmcamera_isp_hdr_bhist_stats44 \
    libmmcamera_isp_ihist_stats46 \
    libmmcamera_isp_linearization40 \
    libmmcamera_isp_ltm47 \
    libmmcamera_isp_luma_adaptation40 \
    libmmcamera_isp_mce40 \
    libmmcamera_isp_mesh_rolloff44 \
    libmmcamera_isp_pdaf48 \
    libmmcamera_isp_pedestal_correct46 \
    libmmcamera_isp_rs_stats46 \
    libmmcamera_isp_scaler_encoder46 \
    libmmcamera_isp_scaler_video46 \
    libmmcamera_isp_scaler_viewfinder46 \
    libmmcamera_isp_sce40 \
    libmmcamera_isp_snr47 \
    libmmcamera_isp_sub_module \
    libmmcamera_le2464c_eeprom \
    libmmcamera_le2464c_master_eeprom \
    libmmcamera_paaf_lib \
    libmmcamera_pdaf \
    libmmcamera_pdafcamif \
    libmmcamera_ppbase_module \
    libmmcamera_ppeiscore \
    libmmcamera_quadracfa \
    libmmcamera_rohm_brcg064gwz_3_eeprom \
    libmmcamera_sunny_ov13855_eeprom \
    libmmcamera_sw2d_lib \
    libmmcamera_thread_services \
    libmmcamera_tintless_algo \
    libmmcamera_tintless_bg_pca_algo \
    libmmcamera_tulip_ov02a10_ofilm_ii \
    libmmcamera_tulip_ov02a10_ofilm_ii_eeprom \
    libmmcamera_tulip_ov02a10_sunny_i \
    libmmcamera_tulip_ov02a10_sunny_i_eeprom \
    libmmcamera_tulip_s5k2l7_ofilm_i \
    libmmcamera_tulip_s5k2l7_ofilm_i_eeprom \
    libmmcamera_tulip_s5k2l7_qtech_ii \
    libmmcamera_tulip_s5k2l7_qtech_ii_eeprom \
    libmmcamera_tulip_s5k3T1_ofilm_ii \
    libmmcamera_tulip_s5k3T1_ofilm_ii_eeprom \
    libmmcamera_tulip_s5k3T1_sunny_i \
    libmmcamera_tulip_s5k3T1_sunny_i_eeprom \
    libmmcamera_tulip_s5k5e8_ofilm_i \
    libmmcamera_tulip_s5k5e8_ofilm_i_eeprom \
    libmmcamera_tulip_s5k5e8_qtech_ii \
    libmmcamera_tulip_s5k5e8_qtech_ii_eeprom \
    libmmcamera_tuning \
    libmmcamera_tuning_lookup \
    libmmjpeg \
    libmmjpeg_interface \
    libmmlib2d_interface \
    libmmqjpeg_codec \
    libmmqjpegdma \
    libmpbase \
    libois_bu63165 \
    libois_lc898122 \
    libqomx_core \
    libqomx_jpegdec \
    libqomx_jpegenc \
    libqomx_jpegenc_pipe \
    libremosaic_daemon \
    libsymphony-cpu \
    libsymphonypower \
    libvideoutils \
    libvidhance \
    libvidhance_gyro \
    fingerprint.fpc.default \
    fingerprint.goodix.default \
    libgf_ca \
    libgf_hal \
    libvendor.goodix.hardware.fingerprint@1.0-service \
    libvendor.goodix.hardware.fingerprint@1.0 \
    FingerprintExtensionService \
    com.fingerprints.extension
